class Person:
    CanId = 9310
    CanCode = "Luong Van Ly"
    CanFullName = "Lương Văn Lý"
    CanDob = None
    CanAddress1 = None
    CanAddress2 = None
    CanEmail = "coolboy90tlhp@gmail.com"
    CanTelNum = "0979182440"
    CanEthnic = None
    CanReligion = None
    CanImgCandi = "dist/img/userIcon.png "
    CreateBy = 42
    CreateDate = "2018-12-21T04:39:21 "
    UpdateBy = 43
    UpdateDate = None
    IsDelete = False
    CanNominee = None
    CateId = None
    CanIsMarried = None
    CanNationality = None
    CanFileCv = "http=//jobbox.vn/Uploads/LuongVanLy.docx"
    CanIdentityName = None
    CanNearestWork = None
    CanSourceProfile = "recruiter"
    CanTimeRecruitment = None
    CanEvaluate = None
    CanNote = None
    CanTalentPoolId = None
    SexCode = "SEX-02"
    RecruitNewsId = None
    GroupRoundId = None
    RoundRecruitId = None
    OrganizationId = 28
    ApplyNo = 1
    CanIdPublish = None
    IsCheckNotifycation = None
    IsCheckWebsite = None
    IsCheckRead = None
    Years = None
    Career = None
    Nominee = None
    IsStatus = None

    Point = None

    FullTexts = None
    Skill = None
    Diploma = None
    Experience = None
    Interest = None
    CompanyNow = None
    WorkNow = None
    FutureGoals = None
    SoftSkill = None
    ReferencePerson = None
    AddressNow = None
    Project = None
    IsUpdate = None
